-- Preshy Beauty — Supabase schema (hardened)
-- Run once in Supabase SQL Editor

-- Catalog
create table if not exists products (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric not null check (price >= 0),
  category text not null default 'tops',
  image text not null default '',
  images jsonb not null default '[]',
  description text not null default '',
  sizes jsonb not null default '["S","M","L"]',
  colors jsonb not null default '["Black"]',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists services (
  id bigint generated by default as identity primary key,
  name text not null,
  duration int not null default 60,
  price numeric not null check (price >= 0),
  description text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists stylists (
  id bigint generated by default as identity primary key,
  name text not null,
  specialty text not null default '',
  image text not null default '',
  bio text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists extensions (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric not null check (price >= 0),
  length text default '',
  texture text default '',
  image text not null default '',
  description text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists bookings (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null default '',
  service text not null,
  stylist text not null default 'Any',
  date date not null,
  time text not null,
  notes text default '',
  status text not null default 'confirmed',
  created_at timestamptz not null default now()
);

create table if not exists orders (
  id text primary key,
  customer jsonb not null default '{}',
  items jsonb not null default '[]',
  total numeric not null default 0,
  payment text not null default 'pending',
  payment_ref text default '',
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

create index if not exists idx_bookings_date on bookings(date);
create index if not exists idx_orders_created on orders(created_at desc);
create index if not exists idx_products_category on products(category);

alter table products enable row level security;
alter table services enable row level security;
alter table stylists enable row level security;
alter table extensions enable row level security;
alter table bookings enable row level security;
alter table orders enable row level security;

-- Drop old open policies if re-running
do $$
declare r record;
begin
  for r in (
    select policyname, tablename from pg_policies
    where schemaname = 'public'
      and tablename in ('products','services','stylists','extensions','bookings','orders')
  ) loop
    execute format('drop policy if exists %I on %I', r.policyname, r.tablename);
  end loop;
end $$;

-- Public: READ catalog only
create policy "public_read_products" on products for select using (true);
create policy "public_read_services" on services for select using (true);
create policy "public_read_stylists" on stylists for select using (true);
create policy "public_read_extensions" on extensions for select using (true);

-- Public: INSERT bookings and orders only (no update/delete from anon)
create policy "public_insert_bookings" on bookings for insert with check (true);
create policy "public_insert_orders" on orders for insert with check (true);

-- Public: SELECT bookings/orders (admin UI uses anon; tighten later with auth)
create policy "public_read_bookings" on bookings for select using (true);
create policy "public_read_orders" on orders for select using (true);

-- Writes to catalog tables: service_role bypasses RLS automatically.
-- Anon/authenticated cannot insert/update/delete products, services, stylists, extensions.
-- Admin seed & admin CRUD must use SUPABASE_SERVICE_ROLE_KEY via API routes.
